### ISSUE TITLE
[cython branch] Value error when using -perm1 -perm2 flags

### ISSUE THREAD

**Issue by samuelfromm** [bjornwallner/DockQ#20]
When using the cython branch, after running 

`DockQ.py <model> <native> -native_chain1 A B -perm1 -perm2`

I get an error (see below). Note that it works fine running  
`DockQ.py <model> <native>`
 or 
`DockQ.py <model> <native> -native_chain1 A -model_chain1 A`

Best
Samuel

The error:
```
Traceback (most recent call last):
File "/proj/berzelius-2021-29/users/x_safro/programs/iTM-align/DockQ.py", line 965, in <module>
main()
File "/proj/berzelius-2021-29/users/x_safro/programs/iTM-align/DockQ.py", line 851, in main
test_info = run_on_groups(
^^^^^^^^^^^^^^
File "/proj/berzelius-2021-29/users/x_safro/programs/iTM-align/DockQ.py", line 635, in run_on_groups
info = calc_DockQ(
^^^^^^^^^^^
File "/proj/berzelius-2021-29/users/x_safro/programs/iTM-align/DockQ.py", line 139, in calc_DockQ
ref_res_distances = get_residue_distances(
^^^^^^^^^^^^^^^^^^^^^^
File "/proj/berzelius-2021-29/users/x_safro/programs/iTM-align/DockQ.py", line 533, in get_residue_distances
model_res_distances = residue_distances(
^^^^^^^^^^^^^^^^^^
File "/proj/berzelius-2021-29/users/x_safro/programs/iTM-align/operations_nocy.py", line 29, in residue_distances
atom_distances = get_distances_across_chains(atom_coordinates1, atom_coordinates2)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/proj/berzelius-2021-29/users/x_safro/programs/iTM-align/operations_nocy.py", line 6, in get_distances_across_chains
distances = ((model_A_atoms[:, None] - model_B_atoms[None, :]) ** 2).sum(-1)
~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
ValueError: operands could not be broadcast together with shapes (4712,1,3) (1,0)
```

**Comment by clami66** [comment]
Hi samuel,

We will soon remove the `-perm` flags, but you can try and check out the version on the `mapping` branch instead.

We have not written a help page yet for this development version, but permutation of chains is automatic in that one. You can also use a new flag `--mapping` to restrict the search if you already know how native/model chains should be paired
