### ISSUE TITLE
Can script calculate the pdb file which only contain alpha-carbon?

### ISSUE THREAD

**Issue by Ming-Qin-tech** [bjornwallner/DockQ#39]
Like this:
ATOM      1   CA ASP B          -2.323   5.946  26.507  1.00  0.00           C 0
ATOM      2   CA PHE B          -2.412   6.084  22.717  1.00  0.00           C 0
ATOM      3   CA VAL B          -5.512   7.481  21.043  1.00  0.00           C 0
ATOM      4   CA LEU B          -6.993   4.827  18.709  1.00  0.00           C 0
ATOM      5   CA ASP B          -8.963   5.019  15.470  1.00  0.00           C 0
ATOM      6   CA ASN B         -12.027   2.837  14.957  1.00  0.00           C 0
ATOM      7   CA GLU B          -9.790   0.105  13.512  1.00  0.00           C 0
ATOM      8   CA GLY B          -7.860  -0.188  16.759  1.00  0.00           C 0
ATOM      9   CA ASN B          -4.681   1.504  15.540  1.00  0.00           C 0
ATOM     10   CA PRO B          -2.867   4.414  17.269  1.00  0.00           C 0
ATOM     11   CA LEU B          -3.469   7.805  15.713  1.00  0.00           C 0
ATOM     12   CA GLU B          -0.425   8.858  13.693  1.00  0.00           C 0
ATOM     13   CA ASN B           1.127  12.247  14.290  1.00  0.00           C 0
ATOM     14   CA GLY B           0.288  14.145  11.095  1.00  0.00           C 0
ATOM     15   CA GLY B          -2.233  11.670   9.700  1.00  0.00           C 0
ATOM     16   CA THR B          -5.665  12.544   8.295  1.00  0.00           C 0
ATOM     17   CA TYR B          -8.811  11.290   9.998  1.00  0.00           C 0

This would output an error:

DockQ /home/u12151002/workspace/DiffDo
ck-PP-main/visualization/DB5_unbound/1AVX/1AVX_r_l_b.model.pdb /home/u12151002/workspace/DiffDock-PP-main/visualization/DB5_u
nbound/1AVX/1AVX_r_l_b.pdb
Traceback (most recent call last):
  File "/home/u12151002/miniconda3/envs/diffdock_pp/lib/python3.10/site-packages/Bio/File.py", line 72, in as_handle
    with open(handleish, mode, **kwargs) as fp:
TypeError: expected str, bytes or os.PathLike object, not TextIOWrapper

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/u12151002/miniconda3/envs/diffdock_pp/lib/python3.10/site-packages/DockQ/DockQ.py", line 684, in load_PDB
    model = pdb_parser.get_structure(
  File "/home/u12151002/miniconda3/envs/diffdock_pp/lib/python3.10/site-packages/DockQ/parsers.py", line 287, in get_structure
    sequences, is_het = self._parse(
  File "/home/u12151002/miniconda3/envs/diffdock_pp/lib/python3.10/site-packages/DockQ/parsers.py", line 306, in _parse
    self.trailer, sequences, is_het = self._parse_coordinates(
  File "/home/u12151002/miniconda3/envs/diffdock_pp/lib/python3.10/site-packages/DockQ/parsers.py", line 374, in _parse_coordinates
    resseq = int(line[22:26].split()[0])  # sequence identifier
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/u12151002/miniconda3/envs/diffdock_pp/lib/python3.10/site-packages/Bio/File.py", line 72, in as_handle
    with open(handleish, mode, **kwargs) as fp:
TypeError: expected str, bytes or os.PathLike object, not TextIOWrapper

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/u12151002/miniconda3/envs/diffdock_pp/bin/DockQ", line 8, in <module>
    sys.exit(main())
  File "/home/u12151002/miniconda3/envs/diffdock_pp/lib/python3.10/site-packages/DockQ/DockQ.py", line 869, in main
    model_structure = load_PDB(
  File "/home/u12151002/miniconda3/envs/diffdock_pp/lib/python3.10/site-packages/DockQ/DockQ.py", line 693, in load_PDB
    model = pdb_parser.get_structure(
  File "/home/u12151002/miniconda3/envs/diffdock_pp/lib/python3.10/site-packages/DockQ/parsers.py", line 35, in get_structure
    self._mmcif_dict = MMCIF2Dict(filename)
  File "/home/u12151002/miniconda3/envs/diffdock_pp/lib/python3.10/site-packages/Bio/PDB/MMCIF2Dict.py", line 35, in __init__
    raise ValueError(
ValueError: The input mmCIF file must begin with a 'data_' directive.

So, when I want to calculate the DockQ of Backbone(alpha-carbon), how can i use this script?

**Comment by clami66** [comment]
Hi, this looks like the PDB you have is not formatted correctly. Judging from the example you pasted, the columns are not formatted as they should, e.g.:

```
ATOM   1964  CA  LYS A   4      14.219   4.348 101.963  1.00  0.00           C  
ATOM   1988  CA  PRO A   5      12.354   4.248  98.681  1.00  0.00           C  
ATOM   2002  CA  ILE A   6      11.732   1.032  96.765  1.00  0.00           C  
ATOM   2021  CA  TRP A   7      14.195   2.020  93.978  1.00  0.00           C  
ATOM   2045  CA  GLU A   8      17.061   2.699  96.438  1.00  0.00           C  
ATOM   2060  CA  GLN A   9      16.322  -0.618  98.179  1.00  0.00           C  
ATOM   2077  CA  ILE A  10      16.534  -2.573  94.906  1.00  0.00           C  
ATOM   2096  CA  GLY A  11      19.510  -0.616  93.639  1.00  0.00           C  
```

It is not a problem to work on CA-only PDBs
