### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by jh2ee** [bjornwallner/DockQ#48]
I got a new error while running dockq.

`
Traceback (most recent call last):
  File "/opt/conda/bin/DockQ", line 8, in <module>
Processing file 225 of 1000: path/to/input.pdb - Result: None
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/DockQ/DockQ.py", line 949, in main
    result_this_mappings = progress_map(
  File "/opt/conda/lib/python3.10/site-packages/parallelbar/parallelbar.py", line 247, in progress_map
    result = _do_parallel(func, 'map', tasks, initializer, initargs, n_cpu, chunk_size, context, total, disable,
  File "/opt/conda/lib/python3.10/site-packages/parallelbar/parallelbar.py", line 157, in _do_parallel
    raise raised_exception
  File "/opt/conda/lib/python3.10/site-packages/parallelbar/parallelbar.py", line 136, in _do_parallel
    result = p.map(func, tasks, chunksize=chunk_size)
  File "/opt/conda/lib/python3.10/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/opt/conda/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
IndexError: tuple index out of range
`

I'm not sure where this error appears.

Now I'm trying to iternate all subdirs in my path and get the dockq score for each subdirs. So I used another multiprocessing to do this (but i made the restraints about the threads)

**Comment by clami66** [comment]
Hi, could you provide the pdb files and command you run so that I can try to reproduce the issue?

**Comment by jh2ee** [comment]
[DQ.zip](https://github.com/user-attachments/files/16762793/DQ.zip)

Here's the one of mine. As you know, I'm trying to iternate all subdirs in my path.
