### ISSUE TITLE
Trying to run Readme example, issues with make command

### ISSUE THREAD

**Issue by chaotify3317** [bjornwallner/DockQ#7]
When I am trying to run the Make command i am getting this:
`cc -O3 -funroll-loops -Isrc/  -c src/molecule.c -lm`
`process_begin: CreateProcess(NULL, cc -O3 -funroll-loops -Isrc/ -c src/molecule.c -lm, ...) failed.`
`make (e=2): The system cannot find the file specified.`
`make: *** [Makefile:14: molecule.o] Error 2`

**Comment by chaotify3317** [comment]
UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init
Traceback (most recent call last):
  File "C:\Users\yspar\DockQ\DockQ.py", line 3, in <module>
    import Bio.PDB
  File "C:\Users\yspar\anaconda3\lib\site-packages\Bio\PDB\__init__.py", line 17, in <module>
    from .PDBParser import PDBParser
  File "C:\Users\yspar\anaconda3\lib\site-packages\Bio\PDB\PDBParser.py", line 16, in <module>
    raise MissingPythonDependencyError(
Bio.MissingPythonDependencyError: Install NumPy if you want to use the PDB parser.

it also says this, although I have already installed Numpy.

**Comment by chaotify3317** [comment]
Nevermind, I figured this out by simply updating my ubuntu.
